config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  root to: 'twtexts#top'
  get '/twtexts', to: 'twtexts#index'
  resources :twtexts do
    collection do
      post :confirm
    end
  end

  resources :users, only: [:new, :create, :show]

  resources :sessions, only: [:new, :create, :destroy]

  resources :favorites, only: [:create, :destroy]

  resources :contacts, only: [:new, :create]
  get '/contacts', to: 'contacts#new'
  
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  validates :content, length: { in: 1..1000 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :twtext
end

app/models/twtext.rb
class Twtext < ApplicationRecord
  validates :content, length: { in: 1..140 }
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,  presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, uniqueness: true,
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :twtexts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_twtexts, through: :favorites, source: :twtext
  mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)
    # ログイン状態ならば、ログインユーザの情報を取得する
    if logged_in?
      @contact.name = current_user.name
      @contact.email = current_user.email
    end
    respond_to do |format|
      if @contact.save
        ContactMailer.contact_mail(@contact).deliver #追記
        format.html { redirect_to twtexts_path, notice: 'お問い合わせが完了しました >>> お問い合わせ受付完了のメールを送信しました' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    favorite = current_user.favorites.create(twtext_id: params[:twtext_id])
    redirect_to twtexts_url, notice: "#{favorite.twtext.user.name}さんのつぶやきをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(twtext_id: params[:twtext_id]).destroy
    redirect_to twtexts_url, notice: "#{favorite.twtext.user.name}さんのつぶやきをお気に入り解除しました"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # ログイン成功の場合
      session[:user_id] = user.id
      redirect_to user_path(user.id), notice: "ログインしました"
    else
      # ログイン失敗の場合
      flash.now[:danger] = 'ログインに失敗しました'
      render 'new'
    end
  end

  def destroy
      session.delete(:user_id)
      flash[:notice] = 'ログアウトしました'
      redirect_to new_session_path
  end

end

app/controllers/twtexts_controller.rb
class TwtextsController < ApplicationController

  before_action :set_twtext, only: [:show, :edit, :update, :destroy]
  before_action :is_login, only: [:new, :edit, :show, :destroy]

  def top
    render 'top'
  end

  def index
    @twtexts = Twtext.all
  end

  def new
    #ビューにデータを渡す(インスタンス変数を定義する)
    if params[:back]
      @twtext = Twtext.new(twtext_params)
    else
      @twtext = Twtext.new
    end
  end

  def confirm
    @twtext = Twtext.new(twtext_params)
    # バリデーション前にユーザIDを格納する
    @twtext.user_id = current_user.id
    render :new if @twtext.invalid?
  end

  def create
    @twtext = Twtext.new(twtext_params)
    @twtext.user_id = current_user.id

    # 画像の復元処理
    if params.has_key?(:cache)
      @twtext.image.retrieve_from_cache! params[:cache][:image]
    end

    if @twtext.save
      # 一覧画面へ遷移
      TwtextMailer.twtext_mail(@twtext).deliver #メール送信
      redirect_to twtexts_path, notice: "新しいつぶやきを投稿しました >>> つぶやき完了のメールを送信しました"
    else
      # 入力フォームを再描画
      render 'new'
    end
  end

  def edit
  end

  def update
    if @twtext.update(twtext_params)
      redirect_to twtexts_path, notice: "つぶやきを編集しました"
    else
      render 'edit'
    end
  end

  def destroy
    @twtext.destroy
    redirect_to twtexts_path, notice: "つぶやきを削除しました"
  end

  def show
    @favorite = current_user.favorites.find_by(twtext_id: @twtext.id)
  end

  private

  # 許可するパラメータを指定するメソッド
  def twtext_params
    params.require(:twtext).permit(:content, :image, :image_cache)
  end

  # idをキーとして値を取得するメソッド
  def set_twtext
    @twtext = Twtext.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :is_login, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # 保存に成功した場合
      session[:user_id] = @user.id
      redirect_to user_path(@user.id), notice: "ユーザ登録が完了しました"
    else
      # 保存に失敗した場合
      render 'new'
    end
  end

  def show
    # ログインユーザのユーザ情報を取得する
    @user = current_user
    # @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  # 未ログインならログイン画面へリダイレクトさせるメソッド
  def is_login
    if !logged_in?
      redirect_to sessions_new_path, notice: "ログインが必要な機能です"
    end
  end


end

app/helpers/twtexts_helper.rb
module TwtextsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_twtexts_path
    elsif action_name == 'edit'
      twtext_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_tw.html.erb
  <div class="list-group-item">
    <div class="media">

      <div class="media-left">
        <%= image_tag('/tw-icon.png') unless twtext.user.image.url %>
        <%= image_tag(twtext.user.image.url, :style => "width: 64px; height: 64px; object-fit: cover;") if twtext.user.image.url %>
      </div>
      <div class="media-body tw_content">
        <span class="label label-default">投稿ユーザ：<%= twtext.user.name %></span>
        <span class="label label-success"><%= "★" * twtext.favorite_users.count %></span>
        <p><%= twtext.content %></p>
        <%= image_tag(twtext.image.url, :class => "img-thumbnail", :width => "300") if twtext.image.url %>
      </div>
      <div class="pull-left">
      </div>
      <div class="pull-right">
        <%= link_to "詳細", twtext_path(twtext.id), class: 'btn btn-default' %>
        <% if twtext.user == current_user %>
          <%= link_to '編集', edit_twtext_path(twtext.id), class: 'btn btn-default' %>
          <%= link_to '削除', twtext_path(twtext.id), class: 'btn btn-danger', method: :delete ,data: { confirm: 'つぶやきを本当に削除しますか？' } %>
        <% end %>
      </div>

    </div>
  </div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>

<% if contact.errors.any? %>
<div class="alert alert-danger alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
    <span aria-hidden="true">×</span></button>
  <strong><%= contact.errors.count %>件のエラーがあります。ご確認ください。</strong>
  <ul>
    <% contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<% if logged_in? %>

<div class="alert alert-info alert-dismissible" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
    <span aria-hidden="true">×</span></button>
    <%= current_user.name %>さんからのお問い合わせを受け付けます
</div>

<% else %>

<div class="input-group input-group-lg">
  <span class="input-group-addon sign-up">名前</span>
  <%= form.text_field :name, id: :contact_email, class: 'form-control', placeholder: "テスト太郎" %>
</div>
<br>
<div class="input-group input-group-lg">
  <span class="input-group-addon sign-up">メールアドレス</span>
  <%= form.email_field :email, id: :contact_email, class: 'form-control', placeholder: "test@sample.com" %>
</div>
<br>

<% end %>

<div class="new_twtext_area input-group input-group-lg">
  <span class="input-group-addon">お問い合わせ内容</span>
  <%= form.text_area :content, class: 'form-control', placeholder: "ここに1000文字以内で入力してください" %>
</div>

<div class="pull-right">
  <%= form.submit "送信する", class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <div class="page-header">
      <h2>お問い合わせ画面
        <small>Contact form</small>
      </h2>
    </div>

    <%= render 'form', contact: @contact %>

  </div>
</div>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TwitterClone</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <header>
      <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
              <span class="sr-only">TwitterClone</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="../">TwitterClone</a>
          </div>

          <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav">
              <li>
                <a href="../">トップ</a>
              </li>
              <li>
                <%= link_to "つぶやき一覧", twtexts_path %>
              </li>
              <% if logged_in? %>
                <li><%= link_to 'つぶやく', new_twtext_path %></li>
                <li><%= link_to "マイページ", user_path(current_user.id) %></li>
                <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
              <% else %>
                <li><%= link_to "新規ユーザ登録", new_user_path %></li>
                <li><%= link_to "ログイン", new_session_path %></li>
              <% end %>
              <li>
                <%= link_to "お問い合わせ", new_contact_path %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <div class="container">

      <%= yield %>
      <br>
    </div>

    <footer class="footer">
      <p class="text-muted text-center">TwitterClone ＋ ImageUploader</p>
      <p class="text-muted text-center">© 2018 Copyright  Tomoyuki Kurosawa</p>
    </footer>

  </body>
</html>

app/views/twtexts/_form.html.erb
<%= form_with(model: @twtext, local: true ,url: choose_new_or_edit, class: 'new_twtext_form' ) do |form| %>

<% if @twtext.errors.any? %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
      <span aria-hidden="true">×</span></button>
    <strong><%= @twtext.errors.count %>件のエラーがあります。ご確認ください。</strong>
    <ul>
      <% @twtext.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="new_twtext_area input-group input-group-lg">
  <span class="input-group-addon">つぶやき内容</span>
  <%= form.text_area :content, class: 'form-control', placeholder: "ここに140文字以内で入力してください" %>
</div>
<div class="input-group input-group-lg">
  <span class="input-group-addon">画像を添付　</span>
  <% if @twtext.image? %>
    <ul class="list-group" style="margin-bottom: 0px;">
      <li class="list-group-item">
        <%= image_tag(@twtext.image.url, :class => "img-thumbnail", :width => "300") %>
      </li>
    </ul>
  <% end %>
  <%= form.file_field :image, class: 'form-control', id: :twtext_image%>
  <%= form.hidden_field :image_cache %>
</div>
<br>
<div class="pull-right">
  <%= form.submit "送信する", class: 'btn btn-primary btn-lg' %>
</div>
<% end %>

app/views/twtexts/confirm.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <div class="page-header">
      <h2>以下のようにつぶやきます
        <small>Confirm</small>
      </h2>
    </div>

    <%= form_with(model: @twtext, url: twtexts_path, local: true) do |form| %>
    <%= form.hidden_field :content %>
    <div class="new_twtext_area input-group input-group-lg">
      <span class="input-group-addon">つぶやき内容</span>
      <%= form.text_area :content, class: 'form-control', readonly: 'readonly' %>
    </div>
    <% if @twtext.image? %>
      <div class="input-group input-group-lg"  style="margin-bottom: 20px;">
        <span class="input-group-addon">画像を添付　</span>
        <ul class="list-group" style="margin-bottom: 0px;">
          <li class="list-group-item">
            <%= image_tag(@twtext.image.url, :class => "img-thumbnail", :width => "300") %>
            <%= hidden_field_tag :"cache[image]", @twtext.image.cache_name %>
          </li>
        </ul>
      </div>
    <% end %>

    <div class="pull-right" style="margin-left: 20px;">
      <%= form.submit "つぶやく", class: 'btn btn-primary btn-lg' %>
    </div>
    <% end %>

    <%= form_with(model: @twtext, url: new_twtext_path, local: true, method: 'get') do |form| %>
      <%= form.hidden_field :content %>
      <%= form.hidden_field :image_cache %>
      <%= hidden_field_tag :"cache[image]",@twtext.image.cache_name if @twtext.image.url %>
    <div class="pull-right">
      <%= form.submit "もどる", class: 'btn btn-default btn-lg', name: 'back' %>
    </div>
    <% end %>

  </div>
</div>

app/views/twtexts/edit.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <div class="page-header">
      <h2>つぶやきを編集します
        <small>Edit tweet</small>
      </h2>
    </div>

    <%= render 'form' %>

  </div>
</div>

app/views/twtexts/index.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <div class="page-header">
      <h1>つぶやき一覧
        <small>List of tweets</small>
        <%= link_to 'つぶやく', new_twtext_path, class: 'btn btn-default btn-lg pull-right hidden-xs col-sm-2' %>
      </h1>
    </div>

    <div class="visible-xs-block">
      <div class="row new_twtext_btn">
        <%= link_to 'つぶやく', new_twtext_path, class: 'btn btn-default btn-lg col-xs-12' %>
      </div>
    </div>

    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
          <span aria-hidden="true">×</span></button>
        <strong>お知らせ</strong> ： <%= flash[:notice] %>
      </div>
    <% end %>

    <div class="list-group">

      <% @twtexts.each do |twtext| %>
        <%= render :partial => "tw", :locals => { twtext: twtext } %>
      <% end %>

    </div>

  </div>
</div>

app/views/twtexts/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <div class="page-header">
      <h2>新しくつぶやきます
        <small>Post a new tweet</small>
      </h2>
    </div>

    <%= render 'form' %>

  </div>
</div>

app/views/twtexts/show.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <div class="page-header">
      <h2>つぶやきの詳細を表示します
        <small>Show a tweet</small>
      </h2>
    </div>

    <div class="list-group">

      <div class="list-group-item">
        <div class="media">

          <div class="media-left">
            <%= image_tag('/tw-icon.png') unless @twtext.user.image.url %>
            <%= image_tag(@twtext.user.image.url, :style => "width: 64px; height: 64px; object-fit: cover;") if @twtext.user.image.url %>
          </div>
          <div class="media-body tw_content">
            <span class="label label-default">投稿ユーザ：<%= @twtext.user.name %></span>
            <p><%= @twtext.content %></p>
            <%= image_tag(@twtext.image.url, :class => "img-thumbnail", :width => "300") if @twtext.image.url %>
          </div>
          <div class="pull-left">
          </div>
          <div class="pull-right">
            <% if @twtext.user == current_user %>
              <%= link_to '編集', edit_twtext_path(@twtext.id), class: 'btn btn-default' %>
              <%= link_to '削除', twtext_path(@twtext.id), class: 'btn btn-danger', method: :delete ,data: { confirm: 'つぶやきを本当に削除しますか？' } %>
            <% end %>
            <% unless @twtext.user == current_user %>
              <% if @favorite.present? %>
                <%= link_to 'お気に入りを解除する', favorite_path(twtext_id: @twtext.id), method: :delete, class: 'btn btn-warning' %>
              <% else %>
                <%= link_to 'お気に入りにする', favorites_path(twtext_id: @twtext.id), method: :post, class: 'btn btn-success' %>
              <% end %>
            <% end %>

          </div>
        </div>
      </div>

        <% if @twtext.favorite_users.present? %>
          <div class="list-group-item">
            <strong><%= @twtext.favorite_users.count %>人がお気に入り</strong>
            <% @twtext.favorite_users.each do |favuser| %>
              <span class="label label-success"><%= favuser.name %></span>
            <% end %>
          </div>
        <% end %>

    </div>
  </div>
</div>

app/views/twtexts/top.html.erb
<br>

<div class="jumbotron">
  <h1>TwitterClone</h1>
  <p>TwitterCloneはつぶやきを投稿できるWebサービスです。</p>
  <p><%= link_to "つぶやきを見る", twtexts_path , class: 'btn btn-default btn-lg' %></p>
  <%= image_tag '/top.jpg' , class: 'topimg' %>
</div>

<div class="row">
  <div class="col-xs-6 col-md-3">
    <a href="#" class="thumbnail">
      <%= image_tag 'http://1.bp.blogspot.com/-nMTqgygyczs/VqtZItHn2_I/AAAAAAAA3ZY/5ZfrZPuZzbY/s180-c/bird_aoitori_bluebird.png' %>
    </a>
    <h3>新たにつぶやく</h3>
    <p>つぶやきを新規投稿できます</p>
  </div>
  <div class="col-xs-6 col-md-3">
    <a href="#" class="thumbnail">
      <%= image_tag 'https://4.bp.blogspot.com/-nkz5J99956U/WWXXC6KF7zI/AAAAAAABFe0/Yn0TrjKgboklRHr07HLPJ6STtn7Oz7yOgCLcBGAs/s180-c/magnifier_animal_inu.png' %>
    </a>
    <h3>つぶやきを見る</h3>
    <p>今までのつぶやきを閲覧できます</p>
  </div>
  <div class="col-xs-6 col-md-3">
    <a href="#" class="thumbnail">
      <%= image_tag 'https://4.bp.blogspot.com/-jKAx5zAsueM/VyNdhthLBhI/AAAAAAAA6OE/zy3ySygYrQwjnIasdi_MPR8_fQBko4B7ACLcB/s180-c/pen_mawashi.png' %>
    </a>
    <h3>つぶやきを直す</h3>
    <p>過去のつぶやきを編集できます</p>
  </div>
  <div class="col-xs-6 col-md-3">
    <a href="#" class="thumbnail">
      <%= image_tag 'https://3.bp.blogspot.com/-yS6U3E7BQ8M/WYAxsys_RUI/AAAAAAABFus/PikB6CIdAM8x4A9OaoH_Gsdtbllpg-CRwCLcBGAs/s180-c/bunbougu_syusei_tape.png' %>
    </a>
    <h3>つぶやきを消す</h3>
    <p>過去のつぶやきを削除できます</p>
  </div>
</div>

app/views/users/new.html.erb
<div class="row">
  <div class="col-md-8 col-md-offset-2">

    <div class="page-header">
      <h2>新規ユーザ登録画面
        <small>Sign up form</small>
      </h2>
    </div>

    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
          <span aria-hidden="true">×</span></button>
        <strong>お知らせ</strong> ： <%= flash[:notice] %>
      </div>
    <% end %>

    <% if @user.errors.any? %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
          <span aria-hidden="true">×</span>
        </button>
        <strong><%= @user.errors.count %>件のエラーがあります。ご確認ください。</strong>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_with(model: @user, local: true) do |f| %>

      <div class="input-group input-group-lg">
        <span class="input-group-addon sign-up">名前</span>
        <%= f.text_field :name, class: 'form-control', placeholder: "テスト太郎" %>
      </div>
      <br>
      <div class="input-group input-group-lg">
        <span class="input-group-addon sign-up">メールアドレス</span>
        <%= f.email_field :email, class: 'form-control', placeholder: "test@sample.com" %>
      </div>
      <br>
      <div class="input-group input-group-lg">
        <span class="input-group-addon sign-up">パスワード</span>
        <%= f.password_field :password, class: 'form-control', placeholder: "password（6文字以上で入力）" %>
      </div>
      <br>
      <div class="input-group input-group-lg">
        <span class="input-group-addon sign-up">パスワード（確認用）</span>
        <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "password（6文字以上で再入力）" %>
      </div>
      <br>

      <div class="input-group input-group-lg">
        <span class="input-group-addon sign-up">アイコン画像（任意）</span>
        <%= f.file_field :image, class: 'form-control', id: :user_image%>
        <%= f.hidden_field :image_cache %>
      </div>
      <br>

      <div class="pull-right">
        <%= f.submit "ユーザ登録", class: 'btn btn-primary btn-lg' %>
      </div>

    <% end %>

  </div>
</div>